<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1dd80b19-8faa-4557-a0e5-43b73dee9470</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.21" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\Deco\source\repos\Helpline.Api\Helpline.Api\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\Deco\source\repos\Helpline.Api\Helpline.Api\.editorconfig" />
  </ItemGroup>

</Project>
